# Object Oriented Programming in Python:

## 1. Classes and Instances:


They allow us to logically group data and function in a way that it is easy to reuse or easy to build upon if needed. Data and functions are analogous to attributes and methods.

Example: We want to represent employees of a company in our python code.

If you want to leave a class empty then use 'pass'

In [ ]:
class Employee:
    pass

Creating Instance of the class Employee:

In [ ]:
emp_1 = Employee()
emp_2 = Employee()

Giving attributes to instances that are unique to them:

In [ ]:
emp_1.first = 'Ameya'
emp_1.last = 'Shanbhag'
emp_1.email = 'ameya.shanbhag@nyu.edu'
emp_1.pay = 50000

emp_2.first = 'Test'
emp_2.last = 'User'
emp_2.email = 'test.user@nyu.edu'
emp_2.pay = 70000

print(emp_1.email)
print(emp_2.email)

ameya.shanbhag@nyu.edu
test.user@nyu.edu


To make this setup automatically when we create Employee we will use ____init____ method inside our class:
In init, they receieve the first argument as the instance itself. Here we call it self.

In [ ]:
class Employee:
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'

Now to create Employees:

In [ ]:
emp_1 = Employee('Ameya','Shanbhag', 50000)
emp_2 = Employee('Test','User', 60000)

print(emp_1.email)
print(emp_2.email)

Ameya.Shanbhag@nyu.edu
Test.User@nyu.edu


If we need to add actions to the class, we need to create methods:
Lets create a method to print the full name of the Employee

In [ ]:
class Employee:
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        
    def fullname(self):
        return '{} {}'.format(self.first,self.last)
emp_1 = Employee('Ameya','Shanbhag', 50000)

print(emp_1.fullname())

Ameya Shanbhag


We have seen what, calling method on instance looks like. Lets see what, calling method on a class looks like:

In [ ]:
print(Employee.fullname(emp_1))

Ameya Shanbhag


## 2. Class Variables:


Class Variables are variables that are shared among all instances of a class. 
Instance variables can be unique for each instance, class variables should be the same for each instance.

Consider you want to give a raise in salary for all the employees. We will use a class variable 'raise_amount' as we will be need to increase the salary of all the employees.

In [ ]:
class Employee:
    
    raise_amount = 1.04
    
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amount) 
        
emp_1 = Employee('Ameya','Shanbhag', 50000)
emp_2 = Employee('test','user', 60000)


print('Before the raise: ',emp_1.pay)
emp_1.apply_raise()
print('After the raise: ',emp_1.pay)

Before the raise:  50000
After the raise:  52000


You can access 'raise_amount' from both, instances and classes too:

In [ ]:
print(Employee.raise_amount)
print(emp_1.raise_amount)
print(emp_2.raise_amount)

1.04
1.04
1.04


In order to access the namespace of any instance use:

In [ ]:
print(emp_1.__dict__)

{'first': 'Ameya', 'last': 'Shanbhag', 'pay': 52000, 'email': 'Ameya.Shanbhag@nyu.edu'}


If you change the raise_amount value using a class, then all the instances and the class itself will have their values changed. For example:

In [ ]:
Employee.raise_amount = 1.05
print(Employee.raise_amount)
print(emp_1.raise_amount)
print(emp_2.raise_amount)

1.05
1.05
1.05


But if you change the raise_amount value using an instance then only that particualr instance will have its value changed:

In [ ]:
class Employee:
    
    raise_amount = 1.04
    
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amount) 
        
        
emp_1 = Employee('Ameya','Shanbhag', 50000)
emp_2 = Employee('test','user', 60000)

emp_1.raise_amount = 1.05
print(Employee.raise_amount)
print(emp_1.raise_amount)
print(emp_2.raise_amount)

1.04
1.05
1.04


This happened because emp_1.raise_amount created another attribute called raise_amount inside the emp_1 instance. So now if you print the namespace of emp_1, you can see that raise_amount is included:

In [ ]:
print(emp_1.__dict__)

{'first': 'Ameya', 'last': 'Shanbhag', 'pay': 50000, 'email': 'Ameya.Shanbhag@nyu.edu', 'raise_amount': 1.05}


We used __self.raise_amount__ instead of __Employee.raise_amount__ in the __apply_raise__ function because that enables us to change the modify the __raise_amount__ for each and every employee i.e the __raise_amount__ need not be constant for all the instances. __So in the above example the pay for emp_1 will be calculated with 1.05 value and the pay for emp_2 will be calculated with 1.04 value.__
____________________________________________________________________________________________________________

But there are a few variables which will be same for all the instances for example the number of employees working for the company. The varialble __num_of_emp__ will be same for all the instances hence we can use __Employee.num_of_emp__ in our method __init__

In [ ]:
class Employee:
    
    raise_amount = 1.04
    num_of_emp = 0
    
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        Employee.num_of_emp += 1
        
        
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amount) 
        
print('No.of employees before: ', Employee.num_of_emp)        
emp_1 = Employee('Ameya','Shanbhag', 50000)
emp_2 = Employee('test','user', 60000)
print('No.of employees after: ', Employee.num_of_emp)

No.of employees before:  0
No.of employees after:  2


## 3. Class Methods and Static Methods:

Regular methods and class automatically take the instance as the first argument. So how can we change this so that it automatically takes the class as the first argument. We use class methods for that. In order to turn a regular method to class method, we just need to add decorator(@classmethod) above the method. For example:

In [ ]:
@classmethod
def set_raise_amount(cls,amount):
    pass

If we want to increase the __raise_amount__ of all the instances then we can create a classmethod which accepts class as an argument. In the following example, I have created a class method in Employee so as soon as I set _Employee.set_raise_amount(1.05)_, it automatically changes the class variable __raise_amount__ from 1.04 to 1.05.

In [ ]:
class Employee:
    
    raise_amount = 1.04
    num_of_emp = 0
    
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        Employee.num_of_emp += 1
        
        
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amount) 
        
    @classmethod
    def set_raise_amount(cls, amount):
        cls.raise_amount = amount
        
emp_1 = Employee('Ameya','Shanbhag', 50000)
emp_2 = Employee('test','user', 60000)
Employee.set_raise_amount(1.05)
print(emp_1.raise_amount)
print(emp_2.raise_amount)

1.05
1.05


Consider you have the data(i.e. First, Last and Pay) in the form of string separated by hyphen and if you want to parse the data then you can create a constructor inside the class Employee which will parse the string.

In [ ]:
class Employee:
    
    raise_amount = 1.04
    num_of_emp = 0
    
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        Employee.num_of_emp += 1
        
        
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amount) 
        
    @classmethod
    def set_raise_amount(cls, amount):
        cls.raise_amount = amount
        
    @classmethod
    def from_string(cls,emp_str):
        first, last, pay = emp_str.split('-')
        return cls(first, last, pay)  # Will create a new Employee and return it.
        
emp1_str = 'Ameya-Shanbhag-50000'
emp1_str_new = Employee.from_string(emp1_str)
print(emp1_str_new.first)
print(emp1_str_new.pay)

Ameya
50000


Regular methods pass the instance as the first argument, Class methods pass the class as the first argument while Static methods do not pass anything (classes or instances) automatically. 

Consider writing a function to check whether its a workday or not. There is a logical connection with the Employee class but it does not depend on the class or the instance variable. So we will make a static method. We say that the method is static if the static method does not use any class or isntances inside the method.

In [ ]:
class Employee:
    
    raise_amount = 1.04
    num_of_emp = 0
    
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        Employee.num_of_emp += 1
        
        
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amount) 
        
    @classmethod
    def set_raise_amount(cls, amount):
        cls.raise_amount = amount
        
    @classmethod
    def from_string(cls,emp_str):
        first, last, pay = emp_str.split('-')
        return cls(first, last, pay)  # Will create a new Employee and return it.
    
    @staticmethod
    def is_workday(day):
        if day.weekday() == 5 or day.weekday() == 6:
            return False
        return True
        
emp1 = Employee('Ameya','Shanbhag','50000')
emp2 = Employee('User','Test','60000')

import datetime
my_date = datetime.date(2016,7,10)

print(Employee.is_workday(my_date)) #The date is Sunday so the ouput is False

False


## 4. Inheritance - Creating Subclasses

Inheritance allows you to inherit attributes and methods from a parent class. This is useful as we can create a subclasses and get all the functionalities of the parent class and then add new functionalities without affecting the parent class. 

Lets say we want to create different types of employees(Manager and Developer). We will create a subclass for each type of employee because they will have the same attributes as the Employee class.


In [ ]:
class Employee:
    
    raise_amount = 1.04
    
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amount) 
        
class Developer(Employee):
    pass
        
emp_1 = Developer('Ameya','Shanbhag', 50000)
emp_2 = Developer('test','user', 60000)

print(emp_1.email)
print(emp_2.email)

Ameya.Shanbhag@nyu.edu
test.user@nyu.edu


If you want to know which class is the subclass accessing, then you can use __help__ command

In [ ]:
print(help(Developer))

Help on class Developer in module __main__:

class Developer(Employee)
 |  Method resolution order:
 |      Developer
 |      Employee
 |      builtins.object
 |  
 |  Methods inherited from Employee:
 |  
 |  __init__(self, first, last, pay)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  apply_raise(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from Employee:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from Employee:
 |  
 |  raise_amount = 1.04

None


If you want to change the __raise amount__ of only the Developer class but use the apply raise function of the Employee class, you will only need to add a variable in the Developer subclass.

In [ ]:
class Developer(Employee):
    raise_amount = 1.10
        
dev_1 = Developer('Ameya','Shanbhag', 50000)
dev_2 = Developer('test','user', 60000)

print(dev_1.pay)
dev_1.apply_raise()
print(dev_1.pay)

50000
55000


If we want every Developer class to have __'programming language'__ as an attribute, we will initialise a __'init'__ method in Developer class and instead of copy pasting first,last,pay and email from Employee class we can just let the Employee class handle the first,last,pay and email and initialise the __programming language__ attribute in the Developer sublclass

In [ ]:
class Developer(Employee):
    raise_amount = 1.10
    def __init__(self, first, last, pay, prog_language):
        super().__init__(first,last,pay)
## Alternative to above method     
##      Employee.__init__(self,first,last,pay)
        
        self.prog_language = prog_language
    
        
dev_1 = Developer('Ameya','Shanbhag', 50000,'Python')
dev_2 = Developer('test','user', 60000,'Java')

print(dev_1.prog_language)
print(dev_2.prog_language)

Python
Java


Similarly,let us create a sublcass __'Manager'__ to keep a track of the employees that are supervised by the Manager

In [ ]:
class Employee:
    
    raise_amount = 1.04
    
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amount) 

class Developer(Employee):
    raise_amount = 1.10
    def __init__(self, first, last, pay, prog_language):
        super().__init__(first,last,pay)
## Alternative to above method     
##      Employee.__init__(self,first,last,pay)
        
        self.prog_language = prog_language

class Manager(Employee):
    def __init__(self, first, last, pay, employees = None):
        super().__init__(first,last,pay)
        if employees is None:
            self.employees = []
        else:
            self.employees = employees
    
    def add_emp(self,emp):
        if emp not in self.employees:
            self.employees.append(emp)

    def remove_emp(self,emp):
        if emp in self.employees:
            self.employees.remove(emp)
            
    def print_emp(self):
        for emp in self.employees:
            print("-->",emp.first)
            
dev_1 = Developer('Ameya','Shanbhag', 50000,'Python')
dev_2 = Developer('test','user', 60000,'Java')

mgr_1 = Manager('Sue','Smith',90000,[dev_1])

print(mgr_1.email)

mgr_1.print_emp()

Sue.Smith@nyu.edu
--> Ameya


Let us try adding one more employee to manager 1

In [ ]:
mgr_1.add_emp(dev_2)
mgr_1.print_emp()

--> Ameya
--> test


Python has two in-built functions i.e. isInstance and isSubClass.

1. __isinstance()__ will tell us if an object is an instance of a class
For example, lets check if __mgr_1__ is an instance of class __Manager__

In [ ]:
print(isinstance(mgr_1,Manager))

True


__issubclass()__ will tell us if a class is a subclass of another.
Lets check if Developer is a subclass of an Employee

In [ ]:
print(issubclass(Developer,Employee))

True


## 5. Special (Magic/Dunder) Methods:

These methods allow us to emulate some built in behaviour within python and its also how we implement operator overloading. By defining the our special methods, we will be able to change the built-in behavior or operation.

In [ ]:
print(emp_1)

As we can see that printing an object gives us a vague looking output. We would be using __dunder__ methods like repr() and str() to modify the output.

__Repr()__ is supposed to be an unambigious representation of the object and can be used for debugging and logging.

__Str()__ is supposed to be readable representation of an object and meant to be used for display to an end-user.

In [ ]:
class Employee:
    
    raise_amount = 1.04
    
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amount) 
        
    def __repr__(self):
        return "Employee('{}','{}',{})".format(self.first,self.last,self.pay)
    
#    def __str__(self):
#        pass
        
emp_1 = Employee('Ameya','Shanbhag', 50000)
emp_2 = Employee('test','user', 60000)

print(emp_1)

Employee('Ameya','Shanbhag',50000)


So as you can see instead of printing some vague object output, with the help of __repr()__ function we were able to modify the output

In [ ]:
class Employee:
    
    raise_amount = 1.04
    
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amount) 
        
    def __repr__(self):
        return "Employee('{}','{}',{})".format(self.first,self.last,self.pay)
    
    def __str__(self):
        return "{} - {}".format(self.first,self.email)
        
emp_1 = Employee('Ameya','Shanbhag', 50000)
emp_2 = Employee('test','user', 60000)

print(emp_1)

Ameya - Ameya.Shanbhag@nyu.edu


As you can see above, the __Str()__ function will be chosen over the __repr()__ function as by definition the __repr()__ function is supposed to be an unambigious representation while __str()__ function is supposed to be human readable. 

## 6. Property Decorators: Getters, Setters and Deleters

In [ ]:
class Employee:
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        
    def fullname(self):
        return '{} {}'.format(self.first,self.last)
emp_1 = Employee('Ameya','Shanbhag', 50000)


print(emp_1.first)
print(emp_1.email)
print(emp_1.fullname())

Ameya
Ameya.Shanbhag@nyu.edu
Ameya Shanbhag


As we can see in the above code, __email__ attribute is dependent on __first and last name__ and similarly the fullname() function. But in the following code lets set the first name to be something else after making an object __emp_1__

In [ ]:
class Employee:
    def __init__(self, first, last, pay):  
        self.first = first
        self.last = last
        self.pay = pay
        self.email = first + '.' + last + '@nyu.edu'
        
    def fullname(self):
        return '{} {}'.format(self.first,self.last)
emp_1 = Employee('Ameya','Shanbhag', 50000)

emp_1.first = 'Vinod'

print(emp_1.first)
print(emp_1.email)
print(emp_1.fullname())

Vinod
Ameya.Shanbhag@nyu.edu
Vinod Shanbhag


We can fix this issue using a Property Decorator. 

A __Property Decorator__ is allows us to define a method that we can access like an attribute. For example, lets pull out this email attribute into a method similar to our fullname() method

In [ ]:
class Employee:
    def __init__(self, first, last):  
        self.first = first
        self.last = last
 
    def email(self):
        return '{}.{}@nyu.edu'.format(self.first,self.last)

    def fullname(self):
        return '{} {}'.format(self.first,self.last)
    
emp_1 = Employee('Ameya','Shanbhag')

emp_1.first = 'Vinod'    

print(emp_1.first)
print(emp_1.email())
print(emp_1.fullname())

Vinod
Vinod.Shanbhag@nyu.edu
Vinod Shanbhag


Now the email method will get the current first and last name but we will also need to change the code where every email attribute is a method call.

This is not what we want. So in order to continue using email as an attribute, we can add a __property decorator__ above a method 'email'. Now lets try running our code using email as an attribute and not as a function. 

In [ ]:
class Employee:
    def __init__(self, first, last):  
        self.first = first
        self.last = last
        
    @property
    def email(self):
        return '{}.{}@nyu.edu'.format(self.first,self.last)

    @property
    def fullname(self):
        return '{} {}'.format(self.first,self.last)
    
emp_1 = Employee('Ameya','Shanbhag')

emp_1.first = 'Vinod'    

print(emp_1.first)
print(emp_1.email)
print(emp_1.fullname)

Vinod
Vinod.Shanbhag@nyu.edu
Vinod Shanbhag


Lets consider that after defining an object 'emp_1', we decide to change the fullname to Vinod Mamta. We cannot change it by 'emp_1.fullname = 'Vinod Mamta' ' as it will give me an error. So in order to do what we want to, we can use __Setters__. In the following code, 'name' corresponds to the full name that has been set by the user. 

In [ ]:
class Employee:
    def __init__(self, first, last):  
        self.first = first
        self.last = last
        
    @property
    def email(self):
        return '{}.{}@nyu.edu'.format(self.first,self.last)

    @property
    def fullname(self):
        return '{} {}'.format(self.first,self.last)
    
    @fullname.setter
    def fullname(self,name):
        first,last = name.split(' ')
        self.first = first
        self.last = last
    
emp_1 = Employee('Ameya','Shanbhag')

emp_1.fullname = 'Vinod Mamta'    

print(emp_1.first)
print(emp_1.email)
print(emp_1.fullname)

Vinod
Vinod.Mamta@nyu.edu
Vinod Mamta


To delete the first and last name, you can use a __Deleter__ decorator.

In [ ]:
class Employee:
    def __init__(self, first, last):  
        self.first = first
        self.last = last
        
    @property
    def email(self):
        return '{}.{}@nyu.edu'.format(self.first,self.last)

    @property
    def fullname(self):
        return '{} {}'.format(self.first,self.last)
    
    @fullname.setter
    def fullname(self,name):
        first,last = name.split(' ')
        self.first = first
        self.last = last
        
    @fullname.deleter
    def fullname(self):
        print('Delete Name!')
        self.first = None
        self.last = None
    
emp_1 = Employee('Ameya','Shanbhag')

emp_1.fullname = 'Vinod Mamta'    

print(emp_1.first)
print(emp_1.email)
print(emp_1.fullname)

del emp_1.fullname

Vinod
Vinod.Mamta@nyu.edu
Vinod Mamta
Delete Name!
